== B. Good quality title

Titles should be consistent and contain meaningful and useful (from
search/discovery perspective) content.

It is difficult to create some automated software assessing the good
quality of the title. May some elements can be verified (avoid acronyms,
….) but the general concensusconsensus is that a guidance should be
developed for WMCP records.

There are two sources:

Below is the NOAA Title Guidance: Style Guidelines A good archival title
summarizes what, where and when data were collected so that a data
consumer can read the title and make an informed decision about learning
more about the data.

* Capitalize all major words (nouns, pronouns, verbs, adjectives,
adverbs, and some conjunctions).
* Avoid using acronyms unless defined in the abstract, especially for
projects or organizations. Exception applies to ``NOAA'' as our audience
is familiar with our acronym.
* If you include an acronym, spell out the meaning of the acronym then
put the acronym in parentheses after the meaning. Do not assume that
everyone reading the title will know or understand all acronyms or
jargon. Some common acronyms may be widely understood within a specific
domain.
* Always, spell out the title acronym at least once in the abstract
text.

WIS Guidance to be referenced here:
